### ISSUE TITLE
New Tag for Symfony 6

### ISSUE THREAD

**Issue by tobilektri** [willdurand/BazingaHateoasBundle#102]
In the master master/composer.json there is support for symfony 6. 

But in the last Release (2.3.0 Latest) from 14 Oct 2021 the composer.json is still fixed on symfony 5.

The same Problem is on https://github.com/willdurand/Hateoas/blob/63e255bb762fd6fa79d973d99ac669daab56c638/composer.json (Latest, Tag: 3.7.0) where the dependency is 
```
"symfony/expression-language": "~3.0 || ~4.0 || ~5.0"
```
and in the master branch the version is 
```
"symfony/expression-language": "~3.0 || ~4.0 || ~5.0 || ~6.0"
```

Is there a plan when the new versions should be tagged so that composer can pull them with symfony 6 support?

The Problem with the pipeline is imho that the pulled release from `willdurand/Hateoas` has not the same `symfony/expression-language` needs with `willdurand/BazingaHateoasBundle` in the master branch

Thank you very much!

**Comment by goetas** [comment]
https://github.com/willdurand/BazingaHateoasBundle/releases/tag/2.4.0
