### ISSUE TITLE
Symfony 7: Service "annotation_reader" is no longer available

### ISSUE THREAD

**Issue by W0rma** [willdurand/BazingaHateoasBundle#108]
I get the following error when using this bundle with symfony 7 and calling `bin/console cache:clear`:

```
The service "hateoas.configuration.metadata.annotation_driver" has a dependency on a non-existent service "annotation_reader".
```

This is because the service "annotation_reader" has been removed in `symfony/framework-bundle:7.0`.

My project doesn't use the annotations defined in https://github.com/willdurand/Hateoas/tree/master/src/Configuration/Annotation at all.

I was able to work around this issue by defining the service "annotation_reader" in my project manually.

It would be nice if annotations could be make optional in this bundle.

Maybe https://github.com/willdurand/BazingaHateoasBundle/pull/104 can help to fix this issue by adding support for native attributes.

**Comment by loic425** [comment]
Any new about this issue?
It blocks sf7 migrations on Sylius.

**Comment by he-lau** [comment]
I have the same error, any idea to correct it please ?

**Comment by gwawrzak** [comment]
Do you have any update on this, please? I can help with some code if needed, please let me know

**Comment by goetas** [comment]
I have merged the lib part, now https://github.com/willdurand/BazingaHateoasBundle/pull/104 should be unblocked, lets wait for the rebase

**Comment by goetas** [comment]
fixed in https://github.com/willdurand/BazingaHateoasBundle/pull/104
