### ISSUE TITLE
JMS Serializer 1.0

### ISSUE THREAD

**Issue by rdohms** [willdurand/BazingaHateoasBundle#46]
jms/serializer and jms/serializer-bundle have gone 1.0.
Can we get a compatible release?

**Comment by piotrantosik** [comment]
see my pr https://github.com/willdurand/BazingaHateoasBundle/pull/43

**Comment by willdurand** [comment]
Done in version [1.0](https://github.com/willdurand/BazingaHateoasBundle/releases/tag/1.0.0).
