### ISSUE TITLE
Symfony 3 not supported because of security.context

### ISSUE THREAD

**Issue by Julien-Marcou** [willdurand/BazingaHateoasBundle#51]
Since Symfony 2.6, the **security.context** service has been deprecated and split into two new services: **security.authorization_checker** and **security.token_storage**.

And now with Symfony 3.0 the **security.context** service has been totally **removed**.

I'm using the BazingaHateoasBundle on a profesionnal Symfony 3 project and got stuck because of that.
There is currently a pull request #50 to solve this problem ;)

**Comment by willdurand** [comment]
Thanks!

**Comment by Julien-Marcou** [comment]
Do you know when a release will be made for this fix ?

**Comment by willdurand** [comment]
done: https://github.com/willdurand/BazingaHateoasBundle/releases/tag/1.1.1.
