### ISSUE TITLE
how to use yaml format

### ISSUE THREAD

**Issue by soerenmartius** [willdurand/BazingaHateoasBundle#53]
Hi,

Instead of using annotations i'd like to use as a configuration file. I've spotted the configuration here https://github.com/willdurand/Hateoas#yaml

Also i've placed a file called hateoas.yml in my bundles config directory but it seems that the bundle isn't autoloading it.

Would you please give me a hint. thanks

**Comment by adrienbrault** [comment]
You have to tell jms serializer bundle where your yaml files are. see http://jmsyst.com/bundles/JMSSerializerBundle/master/configuration

**Comment by soerenmartius** [comment]
excellent! many thanks!
