### ISSUE TITLE
Implement PSR-13

### ISSUE THREAD

**Issue by maennchen** [willdurand/BazingaHateoasBundle#60]
It'd be nice to implement the Relation Classes according to PSR-13. (The PSR ist still in draft, but it could be a good project to test if the draft is complete.)

https://github.com/php-fig/link

**Comment by adrienbrault** [comment]
You should create this issue on https://github.com/willdurand/Hateoas instead. Looking at the psr interfaces, it shouldn't be too tard to add

**Comment by maennchen** [comment]
Ah yes, wrong repo. Closed in favor of willdurand/Hateoas#240
