### ISSUE TITLE
Incorrect version required in composer.json

### ISSUE THREAD

**Issue by solazs** [willdurand/BazingaHateoasBundle#61]
Line 36 of https://github.com/willdurand/BazingaHateoasBundle/blob/master/DependencyInjection/Compiler/ExtensionDriverPass.php results in the following syntax error:

```php
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting
identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in
myapp/vendor/willdurand/hateoas-bundle/Bazinga/Bundle/HateoasBundle/DependencyInjection/Compiler/ExtensionDriverPass.php
on line 36

  [Symfony\Component\Debug\Exception\FatalErrorException]

  Parse Error: syntax error, unexpected 'class' (T_CLASS), expecting
identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
```

PHP 5.4.45-0+deb7u5

Solution is either to correct the required PHP version (5.5 according to [php.net](http://php.net/manual/en/function.get-class.php)) in composer.json, or just provide the interface name as a string.

**Comment by mikaelcom** [comment]
Sorry but why did you close this issue since I just encountered the issue today with this requirement `"willdurand/hateoas-bundle": "^1.0",` that passed under PHP 5.4.40? Did you fix anything matching version ~1.0?
Thx anyway :wink:
