### ISSUE TITLE
Deprectation Notices in Symfony 3.3

### ISSUE THREAD

**Issue by GavChap** [willdurand/BazingaHateoasBundle#67]
I get two deprication messages on the latest version of Symfony

> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "hateoas.configuration.relations_repository" service to "Hateoas\Configuration\RelationsRepository" instead.

> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "hateoas.expression.evaluator" service to "Hateoas\Expression\ExpressionEvaluator" instead.

**Comment by ahilles107** [comment]
Hey, can you check if it's stil valid? I believe that it's solved in #76

**Comment by goetas** [comment]
I beilive this has been solved, If not so, please comment here and I will re open the ticket
