### ISSUE TITLE
500 ERROR

### ISSUE THREAD

**Issue by steve-kouna** [willdurand/BazingaHateoasBundle#68]
I had this error
`{
    "code": 500,
    "message": "The token storage contains no authentication token. One possible reason may be that there is no firewall configured for this URL."
}`
after using 
`
       exclusion = @Hateoas\Exclusion(
           excludeIf = "expr(is_granted(['ROLE_ADMIN']))"
      )
`
**Can anyone help me please**

**Comment by ahilles107** [comment]
This is User code error connected to authorization. Not connected to this bundle. 
Tip: Read more about symfony auth (error message tells you a lot about possible issue), and see how `is_granted` works.
