### ISSUE TITLE
Twig extension loading configuration

### ISSUE THREAD

**Issue by ahilles107** [willdurand/BazingaHateoasBundle#74]
Bundle provides (undocumented) twig extension. Loading it slow downs TwigService initialization in container (as it initialize heavy guzzle client). We should have option to decide if it should be loaded in application (if we want to use it). 

Proposed solution:

* add option to enable it in configuration (default enable for keeping BC). 
* load it only when config is set to true. 

Tell me what do You think about this.

**Comment by ahilles107** [comment]
Pull request is here: https://github.com/willdurand/BazingaHateoasBundle/pull/75 (it fails in travis on SF 4.0 without my changes).

**Comment by ahilles107** [comment]
Resolved in #75

**Comment by mvhirsch** [comment]
> Bundle provides (undocumented) twig extension.

I just stumbled upon this new flag (thanks @ahilles107!). Btw. it's [documented here](https://williamdurand.fr/Hateoas/#linkextension).
