### ISSUE TITLE
Release 1.3.1 or 1.4.0 with latest changes

### ISSUE THREAD

**Issue by ahilles107** [willdurand/BazingaHateoasBundle#77]
I believe that we can release current master as 1.4.0 (with 19 commits).

**Comment by ahilles107** [comment]
@willdurand  - can you look at this issue?

**Comment by willdurand** [comment]
@ahilles107 sure, it is open and next thing in my todo list, I dont have enough bandwidth right now though :(

**Comment by ahilles107** [comment]
Hey, i understand ;) It's just reminder.

**Comment by willdurand** [comment]
Finally done, sorry for the delay: https://github.com/willdurand/BazingaHateoasBundle/releases/tag/1.4.0
